const projects = [
  {index:'CASE 01',title:'Nexo — automação conversacional',intro:'Uma plataforma própria conectada à API oficial da Meta, unindo chatbot, automações operacionais e um agente de IA integrado a modelos de linguagem.',challenge:'A operação de atendimento dependia de uma ferramenta externa instável, com pouca autonomia sobre os fluxos, os dados e a evolução da experiência conversacional.',solution:'Conduzi a construção do Nexo com integração à WhatsApp Cloud API oficial da Meta, motor visual de chatbot, automações configuráveis e agente conectado a uma API de LLM. A solução inclui decisão automática de canal, controle por perfis e auditoria desde o banco de dados.',tags:['Meta API','Chatbot','Agente IA','LLM','Next.js']},
  {index:'CASE 02',title:'NPS com dados auditáveis e leitura por IA',intro:'Dados de satisfação foram reorganizados para gerar indicadores confiáveis e perguntas em linguagem natural sobre o contexto filtrado.',challenge:'O relatório existente apresentava inconsistências de cálculo e classificação que comprometiam a leitura gerencial dos resultados.',solution:'Estruturei normalização auditável, sincronização por Python, regras de acesso e uma camada de análise por IA orientada aos dados selecionados.',tags:['Python','BI','Claude API','ETL'],url:'https://github.com/angelrejansilva-sketch/Nps'},
  {index:'CASE 03',title:'HAAS — vistoria inteligente de equipamentos',intro:'Uma jornada de campo ganhou análise de imagens por IA e uma arquitetura preparada para operar com resiliência.',challenge:'As equipes precisavam registrar e avaliar avarias em equipamentos com rapidez, consistência e uma esteira confiável de entrega.',solution:'Desenhei uma solução React e Node.js com análise de fotos, fallback automático entre modelos Claude, retentativas controladas e deploy com Docker, Kubernetes e CI/CD.',tags:['React','Node.js','Claude','Kubernetes'],url:'https://github.com/angelrejansilva-sketch/haas'},
  {index:'CASE 04',title:'Inventário Técnico — operação de campo',intro:'Uma plataforma para centralizar técnicos, peças, agendamentos, devoluções, divergências e alertas em uma única visão operacional.',challenge:'O controle de inventário e da rede técnica exigia conciliar movimentações, disponibilidade, pendências e histórico entre diferentes fontes e perfis de acesso.',solution:'Construí uma aplicação Next.js com dashboards, trilha de auditoria, gestão de usuários, importações, webhooks e integrações com Supabase e Databricks para dar rastreabilidade à operação.',tags:['Next.js','Supabase','Databricks','Webhooks'],url:'https://github.com/angelrejansilva-sketch/inventario-tecnico'}
];

const caseList=document.getElementById('caseList');
projects.forEach((project)=>{const card=document.createElement('button');card.type='button';card.className='case-card reveal';card.setAttribute('aria-haspopup','dialog');card.innerHTML=`<span>${project.index.replace('CASE ','')}</span><div><h3>${project.title}</h3><div class="case-tags">${project.tags.map(tag=>`<span>${tag}</span>`).join('')}</div></div><p>${project.intro}</p><span class="case-arrow">↗</span>`;card.addEventListener('click',()=>openDialog(project));caseList.appendChild(card)});

const dialog=document.getElementById('caseDialog');
function openDialog(project){document.getElementById('dialogIndex').textContent=project.index;document.getElementById('dialogTitle').textContent=project.title;document.getElementById('dialogIntro').textContent=project.intro;document.getElementById('dialogChallenge').textContent=project.challenge;document.getElementById('dialogSolution').textContent=project.solution;document.getElementById('dialogTags').innerHTML=project.tags.map(tag=>`<span>${tag}</span>`).join('');const link=document.getElementById('dialogProjectLink');link.classList.toggle('visible',Boolean(project.url));if(project.url)link.href=project.url;dialog.showModal()}
document.getElementById('dialogClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});

document.getElementById('year').textContent=new Date().getFullYear();
const progress=document.getElementById('progress');const header=document.getElementById('siteHeader');
function onScroll(){const height=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${height>0?scrollY/height*100:0}%`;header.classList.toggle('scrolled',scrollY>20)}window.addEventListener('scroll',onScroll,{passive:true});onScroll();

const menuButton=document.getElementById('menuButton');const navLinks=document.getElementById('navLinks');menuButton.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});navLinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navLinks.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(item=>observer.observe(item));

const finePointer=matchMedia('(hover:hover) and (pointer:fine)').matches;const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
if(finePointer&&!reduced){const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',event=>{glow.style.opacity='1';glow.style.left=`${event.clientX}px`;glow.style.top=`${event.clientY}px`});const portrait=document.getElementById('portrait');portrait.addEventListener('pointermove',event=>{const rect=portrait.getBoundingClientRect();const px=(event.clientX-rect.left)/rect.width;const py=(event.clientY-rect.top)/rect.height;const x=px-.5;const y=py-.5;portrait.style.setProperty('--mx',`${px*100}%`);portrait.style.setProperty('--my',`${py*100}%`);portrait.style.transform=`perspective(1000px) rotateY(${x*7}deg) rotateX(${-y*7}deg) translateY(-3px)`;portrait.classList.add('is-active')});portrait.addEventListener('pointerleave',()=>{portrait.style.transform='';portrait.classList.remove('is-active')})}
