const projects = [
  {index:'CASE 01',title:'Plataforma própria de automação',intro:'Uma operação crítica deixou de depender de uma ferramenta externa instável e ganhou uma plataforma sob controle do próprio time.',challenge:'A operação de atendimento dependia de uma solução externa com problemas de estabilidade, pouca autonomia e evolução limitada por processo.',solution:'Conduzi a construção de uma plataforma com motor conversacional configurável, decisão automática de canal, controle por perfis e auditoria desde o banco de dados.',tags:['Full Stack','Next.js','Supabase','RPA']},
  {index:'CASE 02',title:'NPS com dados auditáveis e leitura por IA',intro:'Dados de satisfação foram reorganizados para gerar indicadores confiáveis e perguntas em linguagem natural sobre o contexto filtrado.',challenge:'O relatório existente apresentava inconsistências de cálculo e classificação que comprometiam a leitura gerencial dos resultados.',solution:'Estruturei normalização auditável, sincronização por Python, regras de acesso e uma camada de análise por IA orientada aos dados selecionados.',tags:['Python','BI','Claude API','ETL']},
  {index:'CASE 03',title:'Vistoria inteligente de equipamentos',intro:'Uma jornada de campo ganhou análise de imagens por IA e uma arquitetura preparada para operar com resiliência.',challenge:'As equipes precisavam registrar e avaliar avarias em equipamentos com rapidez, consistência e uma esteira confiável de entrega.',solution:'Desenhei uma solução web com análise de fotos, fallback entre modelos de IA, retentativas controladas e publicação conteinerizada.',tags:['React','Node.js','IA','Docker']}
];

const caseList=document.getElementById('caseList');
projects.forEach((project)=>{const card=document.createElement('button');card.type='button';card.className='case-card reveal';card.setAttribute('aria-haspopup','dialog');card.innerHTML=`<span>${project.index.replace('CASE ','')}</span><div><h3>${project.title}</h3><div class="case-tags">${project.tags.map(tag=>`<span>${tag}</span>`).join('')}</div></div><p>${project.intro}</p><span class="case-arrow">↗</span>`;card.addEventListener('click',()=>openDialog(project));caseList.appendChild(card)});

const dialog=document.getElementById('caseDialog');
function openDialog(project){document.getElementById('dialogIndex').textContent=project.index;document.getElementById('dialogTitle').textContent=project.title;document.getElementById('dialogIntro').textContent=project.intro;document.getElementById('dialogChallenge').textContent=project.challenge;document.getElementById('dialogSolution').textContent=project.solution;document.getElementById('dialogTags').innerHTML=project.tags.map(tag=>`<span>${tag}</span>`).join('');dialog.showModal()}
document.getElementById('dialogClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});

document.getElementById('year').textContent=new Date().getFullYear();
const progress=document.getElementById('progress');const header=document.getElementById('siteHeader');
function onScroll(){const height=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${height>0?scrollY/height*100:0}%`;header.classList.toggle('scrolled',scrollY>20)}window.addEventListener('scroll',onScroll,{passive:true});onScroll();

const menuButton=document.getElementById('menuButton');const navLinks=document.getElementById('navLinks');menuButton.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});navLinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navLinks.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(item=>observer.observe(item));

const finePointer=matchMedia('(hover:hover) and (pointer:fine)').matches;const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
if(finePointer&&!reduced){const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',event=>{glow.style.opacity='1';glow.style.left=`${event.clientX}px`;glow.style.top=`${event.clientY}px`});const portrait=document.getElementById('portrait');portrait.addEventListener('pointermove',event=>{const rect=portrait.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width-.5;const y=(event.clientY-rect.top)/rect.height-.5;portrait.style.transform=`perspective(900px) rotateY(${x*9}deg) rotateX(${-y*9}deg)`});portrait.addEventListener('pointerleave',()=>portrait.style.transform='')}
